[buf]
disabled = true

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false

[git_branch]
symbol = " "

[lua]
symbol = " "

[nodejs]
format = 'via $symbol'
symbol = ' '

[package]
disabled = true

[ruby]
symbol = " "
